spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: g12nokona
  sql:
    init:
      mode: always

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
#    web: INFO
#  file:
#    name: app-log.log

server:
  port: 8090
  error:
    whitelabel:
      enabled: false