spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: g12nokona
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
    defer-datasource-initialization: true
  security:
    user:
      name: moderator
      password: $2a$10$IRAa2L42Bz011.za0K6QrevQX2cGHIsbfouKkGdP9OU6S6klTsJn6
      roles: MODERATOR
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
#    web: INFO
#  file:
#    name: app-log.log

server:
  port: 8090
  tomcat:
    relaxed-query-chars: '|, {, }, [, ]'
  error:
    whitelabel:
      enabled: false

openapi:
  title: WEB-service for a warehouse
  description: The service provides a warehouse with complete functionality.
  name: Nikita Zhurkin
  email: zhurkin236@gmail.com

