spring:
  datasource:
    url: jdbc:mysql://localhost:3306/warehouse
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: g12nokona
  sql:
    init:
      mode: always

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          filter:
#            CommonsRequestLoggingFilter: DEBUG
#    web: INFO
#  file:
#    name: app-log.log

server:
  port: 8090
  error:
    whitelabel:
      enabled: false

openapi:
  title: WEB-service for a warehouse
  description: The service provides a warehouse with complete functionality.
  name: Nikita Zhurkin
  email: zhurkin236@gmail.com
